78/xiaozhi-esp32

CMakeLists.txt, main/application.cc, main/boards/kevin-box-2/axp2101.cc, main/boards/kevin-box-2/axp2101.h, main/boards/kevin-box-2/kevin_box_board.cc, main/display/display.cc, versions.py
1、电池放电模式下10分钟自动关机
2、长按电源按钮4秒关机（修复之前无法关机的问题）
=> add power save timer

main/boards/kevin-c3/kevin_box_board.cc, main/idf_component.yml
1、增加C3的efuse设置，不然会没有声音
2、改esp codec dev版本为1.2.0，默认使用1.2.0，避免I2C冲突问题
=> Add esp32c3 efuse setting & fix components version

main/boards/atoms3r-echo-base/README.md, main/boards/m5stack-core-s3/README.md
添加了 `M5Stack CoreS3` 和` AtomS3R + Echo Base` 板子的编译配置指导
=> 添加 sdkconfig 配置指导

main/boards/xmini-c3/xmini_c3_board.cc
目前对话需要按一下按键，体验不太友好，所以增加单击按键触发连续对话。
=> 增加 虾哥mini-c3单击按键触发连续对话

main/boards/esp-box-3/esp_box3_board.cc, main/boards/esp-sparkbot/esp_sparkbot_board.cc, main/boards/lichuang-c3-dev/lichuang_c3_dev_board.cc, main/boards/lichuang-dev/lichuang_dev_board.cc, main/boards/magiclick-2p4/magiclick_2p4_board.cc, main/boards/magiclick-c3/magiclick_c3_board.cc, main/boards/movecall-moji-esp32s3/movecall_moji_esp32s3.cc, main/boards/taiji-pi-s3/taiji_pi_s3.cc, main/display/display.h, main/display/lcd_display.cc, main/display/lcd_display.h, main/display/no_display.h, main/iot/things/blaklight.cc
=> iot增加屏幕背光亮度调节

main/boards/esp-sparkbot/chassis.cc, main/boards/esp-sparkbot/config.h, main/boards/esp-sparkbot/esp_sparkbot_board.cc, main/iot/things/chassis.cc
支持 ESP SparkBot 坦克底座的控制
- 跳舞
- 左转
- 右转
- 前进
- 后退
- 灯光效果
=> feat: Add ESP SparkBot tracked chassis Support

main/boards/esp32-s3-touch-lcd-1.46/esp32-s3-touch-lcd-1.46.cc, main/boards/esp32-s3-touch-lcd-1.85/esp32-s3-touch-lcd-1.85.cc, main/boards/esp32-s3-touch-lcd-1.85c/esp32-s3-touch-lcd-1.85c.cc, main/boards/esp32s3-korvo2-v3/esp32s3_korvo2_v3_board.cc
=> 改korvo板lcd cs引脚为NC，使用TCA9554扩展的IO3来拉低控制LCD CS

main/boards/magiclick-c3-v2/config.json, main/boards/magiclick-c3-v2/magiclick_c3_v2_board.cc, main/boards/magiclick-c3/config.json, main/boards/magiclick-c3/magiclick_c3_board.cc
=> 给magiclick-c3系列板子增加低功耗模式

main/boards/m5stack-core-s3/m5stack_core_s3.cc
Add M5CoreS3 IoT support (Backlight & Battery )
=> Add M5CoreS3 IoT support

main/boards/atoms3-echo-base/atoms3_echo_base.cc, main/boards/atoms3r-echo-base/atoms3r_echo_base.cc
=> add atoms3r backlight iot support

main/boards/lilygo-t-cameraplus-s3/README.md, main/boards/lilygo-t-cameraplus-s3/lilygo-t-cameraplus-s3.cc, main/boards/lilygo-t-cameraplus-s3/tcamerapluss3_audio_codec.cc, main/boards/lilygo-t-circle-s3/README.md, main/boards/lilygo-t-circle-s3/lilygo-t-circle-s3.cc, main/boards/lilygo-t-circle-s3/tcircles3_audio_codec.cc
=> 增加LilyGo T-Circle-S3和T-CameraPlus-S3的屏幕背光和低功耗模式

scripts/release.py
feat: 使用Python标准库zipfile解决系统找不到zip命令导致无法打包的问题
=> feat: 使用Python标准库zipfile解决系统找不到zip命令导致无法打包的问题

scripts/p3_tools/p3_gui_player.py
一个简易的P3文件播放器，使用Python标准库Tkinter
=> add: GUI版P3文件简易播放器

main/boards/du-chatx/du-chatx-wifi.cc, main/boards/du-chatx/power_manager.h
重新整理了一下代码规范。可能VSCODE 的自动格式工具的原因。手工整理了一下，不知道能不能通过。
=> 重新整理了代码规范。去掉了一部分多余代码。

main/boards/sensecap-watcher/sensecap_watcher.cc
spd2010这个屏幕，每次刷新的行数需要是4的倍数，否则会显示异常。
将lvgl display的刷新行数修改为4的倍数就正常了。
修改前，显示有异常：
修改后，显示正常：
=> 解决sensecap-watcher显示异常

main/boards/df-k10/k10_audio_codec.cc
=> fix: 解决行空板df-k10麦克风收音太小的问题

main/Kconfig.projbuild, main/display/lcd_display.cc
lcd_display增加深色模式选项,微信风格和原有风格都支持。
=> add dark mode

main/boards/magiclick-2p4/magiclick_2p4_board.cc, main/boards/magiclick-2p5/config.json, main/boards/magiclick-2p5/magiclick_2p5_board.cc, main/boards/magiclick-2p5/power_manager.h
=> 更新神奇按钮S3系列功能

.github/workflows/build.yml
增加github action编译机支持，
当提交代码后，github会启动编译，并在编译不过时邮件通知你。
=> add ci build.yml

main/boards/common/sy6970.cc, main/boards/common/sy6970.h, main/boards/lilygo-t-cameraplus-s3/README.md, main/boards/lilygo-t-cameraplus-s3/config.h, main/boards/lilygo-t-cameraplus-s3/config.json, main/boards/lilygo-t-cameraplus-s3/lilygo-t-cameraplus-s3.cc, main/boards/lilygo-t-cameraplus-s3/tcamerapluss3_audio_codec.cc, main/boards/lilygo-t-circle-s3/config.h, main/boards/lilygo-t-circle-s3/tcircles3_audio_codec.cc
参考了Sy6970 datasheet和小智其他板子的写法，以及如下两个项目：
https://github.com/Xinyuan-LilyGO/T-CameraPlus-S3/blob/arduino-esp32-libs_V2.0.14/examples/Lvgl_UI/SY6970.cpp
https://github.com/lewisxhe/XPowersLib/blob/master/src/PowersSY6970.tpp
=> lilygo-t-cameraplus-s3增加电源管理

main/boards/minsi-k08-dual/minsi_k08_dual.cc, main/boards/minsi-k08-dual/power_manager.h
=> fix power manager error

main/boards/df-k10/config.h, main/boards/df-k10/config.json, main/boards/df-k10/df_k10_board.cc
为df-k10增加视觉识别功能适配
测试视频：https://b23.tv/tzX4bBq
视频可能正在审核中
=> feature: Add dfrobot-k10 vision recognition

main/boards/df-k10/df_k10_board.cc
=> 调整df-k10摄像头拍照方向

main/boards/esp-sparkbot/esp_sparkbot_board.cc
=> feat: 使用 MCP 控制 ESP-SparkBot 的摄像头方向

main/boards/zhengchen-1.54tft-ml307/zhengchen-1.54tft-ml307.cc, main/boards/zhengchen-1.54tft-wifi/zhengchen-1.54tft-wifi.cc
=> hide low_battery

.gitignore, main/CMakeLists.txt, main/boards/esp-hi/esp_hi.cc, main/idf_component.yml
- 添加缓存策略，避免重复拉取表情动画
- 添加 ESP-Hi WebUI
=> feat: 添加 ESP-Hi WebUI

main/boards/esp32-s3-touch-lcd-3.5/config.h, main/boards/esp32-s3-touch-lcd-3.5/config.json, main/boards/esp32-s3-touch-lcd-3.5/esp32-s3-touch-lcd-3.5.cc
=> 添加了摄像头和触控支持

main/boards/esp-hi/esp_hi.cc
优化 ESP-Hi 的 MCP Tools 数量
关联 https://github.com/78/xiaozhi-esp32/pull/790 https://github.com/78/xiaozhi-esp32/pull/797
=> fix: 优化 ESP-Hi 的 MCP Tools 数量

main/boards/sensecap-watcher/README.md, main/boards/sensecap-watcher/README_en.md, main/boards/sensecap-watcher/config_en.json, scripts/release.py
=> feat: Support choosing different config.json

main/boards/echoear/EchoEar.cc, main/idf_component.yml
EchoEar 在配网模式下触摸屏幕时可能 crash，此 PR 修复了上述问题。
=> 修复 EchoEar 配网模式下潜在的 crash

main/display/esplog_display.h
很遗憾，在刚学一点git知识后提交的上一个拉取请求存在bug(影响较小)，经历过分叉、变基、创建分支后，一切都向好发展了。
=> 规范函数名,修复一个重写错误

main/Kconfig.projbuild, main/audio/wake_words/afe_wake_word.cc, main/audio/wake_words/afe_wake_word.h, main/audio/wake_words/custom_wake_word.cc, main/audio/wake_words/custom_wake_word.h, main/audio/wake_words/esp_wake_word.cc, main/audio/wake_words/esp_wake_word.h, main/idf_component.yml
=> Add custom wakeword threshold option

scripts/license_tools/esp32_production_tool.py, scripts/license_tools/run_tool.bat
1. 改为线程池加异步处理subprocess
2. windows下检验COM, windows下直接使用`esptool`而不是`esptool.py`
3. 布局动态, 线程持续读取刷新然后仅打印存在的端口, 只对新增端口进行整个流程
=> refactor: 对界面改动成动态的/支持windows

.github/workflows/build.yml
fix bug in https://github.com/78/xiaozhi-esp32/pull/1028
=> fix: ci idf.py not found

scripts/acoustic_check/demod.py, scripts/acoustic_check/graphic.py, scripts/acoustic_check/main.py, scripts/acoustic_check/readme.md, scripts/acoustic_check/requirements.txt
1. 添加一个scripts下的gui程序用于实时查看传入信号的频率分布
2. readme.md中展示了配网页面以及部分设备的测试结果
=> 添加python scripts声音检测的可视化GUI以及声波解调的准确度

main/boards/yunliao-s3/power_manager.cc, main/boards/yunliao-s3/yunliao_s3.cc
1.修正4G模式无法启动模块bug
2.修正长按开机及容易关机bug
3.修正每次开机电量低告警bug
=> fix:小智云聊some bugfix

main/boards/esp32s3-korvo2-v3/esp32s3_korvo2_v3_board.cc
for issue https://github.com/78/xiaozhi-esp32/issues/1254
=> Change the button array to ADC buttons as in the board for esp32s3-korv2
