main/audio_codecs/es8311_audio_codec.cc
main/audio_codecs/es8311_audio_codec.h

1、增加了对PA的控制
2、增加esp_codec_set_disable_when_closed控制
3、避免了关闭输出时输入被关闭，无法唤醒的问题

fix:es8311 share i2s wake bug

---

main/boards/bread-compact-esp32/config.h
main/boards/bread-compact-esp32/esp32_bread_board.cc

新增 ESP32 系列开发板 对 OLED-0.96 SSD1306 屏幕显示的支持
已自测验证OK
邀请数位网友验证OK
1. 支持 ESP32 系列开发板: DevKitC / NodeMcu-32S / GoouuuESP32 / ESP32 DoIt / ESP-32S
2. 注意: 非ESP32-C3 / 非ESP32-S3

新增 ESP32 系列开发板 对 OLED-0.96 SSD1306 屏幕显示的支持

---

main/boards/atoms3r-echo-base/atoms3r_echo_base.cc

你好，尝试添加了 AtomS3R + Atomic Echo Base 的底座的连接检测
底座未连接时会显示提示页面，而不再是无限重启：

添加 AtomS3R 未连接底座提示页面

---

main/boards/atoms3-echo-base/atoms3_echo_base.cc

修复了之前 PR 提到的问题： https://github.com/78/xiaozhi-esp32/pull/154

修复 AtomS3 屏幕 RGB 顺序

---

main/application.cc
main/application.h
main/boards/bread-compact-esp32/config.h
main/boards/bread-compact-esp32/esp32_bread_board.cc

外接唤醒模组的支持，好处是可以有多种自定义唤醒词，进行唤醒小智
ESP32(非C3，非S3) 面包板上已支持
本人测试采用ASR-ProV1.0版本的唤醒模组，测试内容包括：自定义唤醒词，唤醒词打断，唤醒词回应
邀请2位同型号群友测试通过，邀请1位型号是HLK-V20的群友测试通过。
此代码兼容其他型号的唤醒模组，并没做限制模组型号，方便大家使用。

外接唤醒模组的支持，可以有多种自定义唤醒词，进行唤醒小智，ESP32(非C3，非S3) 面包板上已支持

---

main/boards/esp32-s3-touch-amoled-1.8/esp32-s3-touch-amoled-1.8.cc

Add backlight control logic code to Waveshare ESP32-S3-Touch-AMOLED-1.8. The code has been tested.
I won't update any new features until the next major feature change.
Happy coding, everyone!

Add backlight control logic code to Waveshare ESP32-S3-Touch-AMOLED-1.8

---

main/boards/xingzhi-cube-0.96oled-ml307/xingzhi-cube-0.96oled-ml307.cc
main/boards/xingzhi-cube-0.96oled-ml307/xingzhi_ssd1306_display.cc
main/boards/xingzhi-cube-0.96oled-ml307/xingzhi_ssd1306_display.h
main/boards/xingzhi-cube-0.96oled-wifi/xingzhi-cube-0.96oled-wifi.cc
main/boards/xingzhi-cube-0.96oled-wifi/xingzhi_ssd1306_display.cc
main/boards/xingzhi-cube-0.96oled-wifi/xingzhi_ssd1306_display.h
main/boards/xingzhi-cube-1.54tft-ml307/xingzhi-cube-1.54tft-ml307.cc
main/boards/xingzhi-cube-1.54tft-ml307/xingzhi_lcd_display.cc
main/boards/xingzhi-cube-1.54tft-ml307/xingzhi_lcd_display.h
main/boards/xingzhi-cube-1.54tft-wifi/xingzhi-cube-1.54tft-wifi.cc
main/boards/xingzhi-cube-1.54tft-wifi/xingzhi_lcd_display.cc
main/boards/xingzhi-cube-1.54tft-wifi/xingzhi_lcd_display.h

基于display.h文件为星智开发板四个板级配置分别集成新的display文件，将oled屏幕的聊天信息显示改为滚动显示，加入了电量显示和睡眠功能

为星智开发板四个板级配置分别集成新的display文件，将oled屏幕的聊天信息显示改为滚动显示，加入了电量显示和睡眠功能

---

main/Kconfig.projbuild
main/audio_codecs/no_audio_codec.cc
main/audio_codecs/no_audio_codec.h

在原有的no_audio_codec中，使用了通用的NoAudioCodec::Read()，但是并不适用于I2S的PDM通信模式，导致录音数据采样率异常(从小智后台播放历史对话声音可以得知)，因此唤醒词无法正常使用，且声纹识别也无法正确匹配。
根据乐鑫官方文档：[API 参考](https://docs.espressif.com/projects/esp-idf/zh_CN/stable/esp32s3/api-reference/index.html) » [外设 API](https://docs.espressif.com/projects/esp-idf/zh_CN/stable/esp32s3/api-reference/peripherals/index.html) » [I2S](https://docs.espressif.com/projects/esp-idf/zh_CN/stable/esp32s3/api-reference/peripherals/i2s.html)
> PDM RX 只在 I2S0 中受支持，且只支持 16 位宽的采样数据。
因此添加配置项，当麦克风使用PDM时，需要针对性的读取处理。

修复麦克风PDM数据位宽读取bug，唤醒也能正常使用

---

main/protocols/protocol.cc

修改了protocol.cc文件中的SendIotDescriptors方法，实现将待发送的消息拆分后发送，以解决4g模块在mqtt发布消息过长时导致的网络异常的问题

修改了protocol.cc文件中的SendIotDescriptors方法，实现将待发送的消息拆分后发送，以解决4g模块在mqtt发布消息过长时导致的网络异常的问题

---

scripts/release.py

1.解决第一次源码编译，由于本地不存在`release`文件夹,导致的zipfile报错问题：  
```  
board type: bread-compact-wifi
project version: 1.4.7
Traceback (most recent call last):
File "E:\xiaozhiAI\soureCode\xiaozhi-esp32\scripts\release.py", line 133, in <module>
release_current()
File "E:\xiaozhiAI\soureCode\xiaozhi-esp32\scripts\release.py", line 48, in release_current
zip_bin(board_type, project_version)
File "E:\xiaozhiAI\soureCode\xiaozhi-esp32\scripts\release.py", line 37, in zip_bin
with zipfile.ZipFile(output_path, 'w') as zipf:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "zipfile.py", line 1281, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'releases/v1.4.7_bread-compact-wifi.zip'
```
2. 增加`compression`参数，使用默认的压缩级别（默认为6），避免压缩包太大问题，使用后压缩包体积和调用系统`zip`指令生成的压缩包体积相当。

feat:解决第一次编译，报错，找不到release路径的问题

---

main/boards/common/backlight.cc
main/boards/kevin-yuying-313lcd/esp_lcd_gc9503.h

1、降低pclk频率，OTA后发现会有屏幕偏移 
2、再次增大背光PWM频率防止电感啸叫

调整鱼鹰3.13开发板：1、降低pclk频率 2、增大背光PWM频率防止电感啸叫

---

main/Kconfig.projbuild
main/boards/bread-compact-wifi-lcd/compact_wifi_board_lcd.cc
main/display/lcd_display.cc
main/display/lcd_display.h

项目配置中可以选择使用在LCD面板使用微信聊天样式
因为使用表情图标移动到右上角，所以建议在使用微信聊天模式的时候，表情符号改为30号字体。

在LCD面板使用微信聊天样式。

---

main/display/lcd_display.cc

微信ui在消息数量超过上限后，会删除最早的消息
删除最早的消息会导致所有气泡整体往上移
所以需要重新滚动到当前消息气泡位置

fix: 修复微信ui在消息数量超过上限后，气泡位置向上偏移的问题

---

main/idf_component.yml

Fix Sh1106 Compile Error Bug. 
IDF 5.3.2 Not supporting sh1106-esp-idf.

Fix Sh1106 Compile Error Bug. IDF 5.3.2 Not supporting sh1106-esp-idf.

---

main/boards/bread-compact-esp32-lcd/esp32_bread_board_lcd.cc

Fix ESP32 Board Led No Light Bug
Dev Board  GPIO2 LED  No Light ，Because GetLed has been implemented

Fix ESP32 Board Led No Light Bug

---

main/boards/atk-dnesp32s3-box/atk_dnesp32s3_box.cc
main/boards/atk-dnesp32s3/atk_dnesp32s3.cc

修复正点原子开发板XL9555驱动 Port1 无法正确输出的问题

修复正点原子开发板XL9555驱动 Port1 无法正确输出的问题

---

main/boards/lichuang-dev/lichuang_dev_board.cc
main/idf_component.yml

add lcd touch for lichuang_dev

---

main/boards/esp32-s3-touch-amoled-1.8/esp32-s3-touch-amoled-1.8.cc

给微雪电子ESP32-S3-Touch-AMOLED-1.8添加触控支持

add lcd touch for esp32-s3-touch-amoled-1.8

---

main/boards/esp32-s3-touch-lcd-3.5/esp32-s3-touch-lcd-3.5.cc

部分esp32-s3-touch-lcd-3.5开机黑屏不显示，在初始化lcd后对ESP32进行软复位后才能解决这个问题，麻烦帮忙审阅一下。

解决部分esp32-s3-touch-lcd-3.5开机黑屏不显示的问题

---

main/boards/waveshare-p4-nano/esp32-p4-nano.cc
main/display/lcd_display.cc
main/idf_component.yml

Last Pr https://github.com/78/xiaozhi-esp32/pull/589 I cancelled the component requirement in the yml file, which was wrong. So I re-opened the PR, now the dependency package is complete, you can normally select ESP32-P4 target compilation

Adjust dependency components for ESP32-P4

---

main/boards/waveshare-s3-touch-amoled-1.75/esp32-s3-touch-amoled-1.75.cc

Because the screen supplier modifies the screen internal software, some registers are now added to adapt to the screen changes

Add some register configuration for 1.75 amoled screen 

---

main/boards/atk-dnesp32s3/atk_dnesp32s3.cc
main/boards/atk-dnesp32s3/config.h

atk_dnesp32s3添加了相机：
-----------------涉及文件-------------------
config.h: 添加相机引脚定义
atk_dnesp32s3.cc : 添加 InitializeCamera()
----------------------------------------------
依据正点原子官方例程参数。
在ov2640模组上测试通过。

正点原子DNESP32S3开发板新增相机（ov2640）

---

main/idf_component.yml

更新 ADC MIC 版本，将默认的软件增益从 16x 改成 8x，极大的优化了唤醒成功率。并支持更改增益大小

feat(esp-hi): update adc mic version

---

main/boards/esp-hi/config.json
main/idf_component.yml

1. 双唤醒词效果很差，去掉了 hi lexin
2. 修改错误的舵机初始角度
3. 更新舵机控制程序组件版本

fix(esp-hi): fix can not wake up

---

main/boards/esp-hi/config.json
main/boards/esp-hi/esp_hi.cc

关联 https://github.com/78/xiaozhi-esp32/pull/790
扩大 Main Task Stack Size 之后还是有概率在启动时爆栈，新增了一些缓解措施。

fix: 延迟 ESP-Hi WebUI 启动时间

---

main/audio_codecs/es8311_audio_codec.cc
main/audio_codecs/es8311_audio_codec.h

有些功放的使能引脚比如TC8002D，低电平为开，高电平为关。
所以我添加了一个pa_inverted参数，在为false时，低电平为关，高电平为开；为true时，低电平为开，高电平为关。
该参数默认为false，所以添加该参数不会影响以前的板子。

feat: es8311添加功放使能引脚的反向控制

---

main/boards/atoms3-echo-base/atoms3_echo_base.cc
main/boards/common/backlight.cc
main/boards/common/backlight.h

因为 [AtomS3](https://docs.m5stack.com/zh_CN/core/AtomS3) 的背光控制不支持高频 PWM，所以在 `PwmBacklight` 上加了频率的传参

修复 AtomS3 背光控制

---

main/boards/esp-hi/adc_pdm_audio_codec.cc

@laride 看看这个，PDM mic 在 open 之后，如果 close 会崩溃

fix esp-hi crashing in esp_codec_dev_close()

---

main/audio/audio_service.cc
main/boards/esp-hi/adc_pdm_audio_codec.cc
main/boards/esp-hi/emoji_display.cc
main/boards/esp-hi/esp_hi.cc
main/idf_component.yml

- 修复 https://github.com/78/xiaozhi-esp32/pull/984 `esp_codec_dev_close()` 后 crash 的问题。
- 修复在选择其他语言时，屏幕表情不能正常切换的问题。
- 缓解 esp-hi 的扬声器底噪。

fix: resolve some audio issues on esp-hi

---

main/boards/lichuang-dev/lichuang_dev_board.cc

Corrected the misconfigured touchscreen parameters of lichuang_S3_dev, which caused touch offset.
.x_max = DISPLAY_WIDTH,
.y_max = DISPLAY_HEIGHT,
This parameter conflicts with the configuration   (.swap_xy = 1) .
fix to：
.x_max = DISPLAY_HEIGHT,
.y_max = DISPLAY_WIDTH,

fix: Correct the touch offset of lichuang_S3_dev

---

main/Kconfig.projbuild
main/application.cc
main/audio/wake_words/custom_wake_word.cc
main/idf_component.yml
scripts/build_default_assets.py

This pull request focuses on improving configuration clarity, internationalization, and flexibility for board, display, and wake word options, as well as updating supporting scripts for multi-model support. The most significant changes are the addition of a unified wake word selection mechanism, clearer and more consistent option naming (including English translations), and enhancements to the asset build script to handle multiple models.
**Configuration and Option Naming Improvements:**
* Standardized and clarified board and display names in `main/Kconfig.projbuild` to use more descriptive and English-friendly labels, improving readability and internationalization. [[1]](diffhunk://#diff-693eca413d2fc950032252b588a85081f1533bac322dac62aec7a5220e429d77L89-R119) …

fix multiple wakenet words and custom wake word

---

main/audio/audio_codec.cc
main/audio/audio_codec.h
main/audio/codecs/box_audio_codec.cc
main/audio/codecs/es8311_audio_codec.cc
main/audio/codecs/es8374_audio_codec.cc
main/audio/codecs/es8388_audio_codec.cc
main/audio/codecs/es8389_audio_codec.cc
main/audio/codecs/no_audio_codec.cc
main/boards/m5stack-core-s3/cores3_audio_codec.cc
main/boards/m5stack-tab5/tab5_audio_codec.cc

This pull request introduces a unified and configurable input gain system for all audio codec classes, replacing hardcoded microphone gain values. It adds an `input_gain_` member to the base `AudioCodec` class, provides a setter method, and ensures that each codec uses this member for setting input gain. Additionally, it improves the `NoAudioCodec` and `NoAudioCodecSimplexPdm` classes by implementing input gain amplification in software. These changes make audio input gain more flexible and easier to manage across different hardware implementations.
**Input Gain Refactor and Configuration**
* Added `input_gain_` member variable and corresponding getter/setter (`SetInputGain`, `input_gain`) to the base `AudioCodec` class, allowing input gain to be set and queried in a unified way. …

Add SetInputGain(float gain) to AudioCodec
